# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - adf_publish
  paths:
    include:
    - ADF_Publish/*

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: CopyFiles@2
  displayName: Copy artifacts to stage location for develop branch
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/ADF_Publish/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true


- task: PublishBuildArtifacts@1
  displayName: Publishing artifacts for CDPData-adf-SBPOC  
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/ADF_Publish'
    ArtifactName: 'CDPData-adf-SBPOC'
